name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install `uv`
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install Dependencies using `uv sync`
        run: |
          uv sync

      - name: Build the package
        run: |
          uv build

      - name: Publish package to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo -e "__token__\n${PYPI_API_TOKEN}" | uv publish